// Exceptions Exercise 1
// Fill in the missing parts to output an error message if an error occurs.

using System;

try
{
  int[] myNumbers = {1, 2, 3};
  Console.WriteLine(myNumbers[10]);
}
catch (Exception e)
{
  Console.WriteLine(e.Message);
}

// Exceptions Exercise 2
// Fill in the missing parts to execute some code, after the exception statements, regardless of the result.

using System;


try
{
  int[] myNumbers = {1, 2, 3};
  Console.WriteLine(myNumbers[10]);
}
catch (Exception e)
{
  Console.WriteLine("Something went wrong.");
}
finally
{
  Console.WriteLine("The 'try catch' is finished.");
}
